name:                monadtrans
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/monadtrans#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2022 Author name here
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - transformers

ghc-options:
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields

executables:
  monadtrans:
    source-dirs:      src/Trans
    main:             Main.hs

  reader:
    source-dirs:      src/SR
    main:             Main.hs

  state:
    source-dirs:      src/State
    main:             Main.hs

